### ISSUE TITLE
Delivery Weekend roadmap

### ISSUE THREAD

**Issue by arthurphilippe** [arthurphilippe/cpp_arcade#68]
We need :
- [x] a map ready for solarfox in order to add the game's logic #61; 
- [ ] the last Display library up and working (SDL);
- [x] that the ghosts in pacman turn blue when the `_fever` is set to true;
- [x] that there is no duplicates in the `GfxLibs` of the `startup` #67.
